services:
#  workout:
#    restart: always
#    image: workout:latest
#    network_mode: host
#    environment:
#      POSTGRES_HOST: ${POSTGRES_HOST}
#      POSTGRES_PORT: ${POSTGRES_PORT}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
#      POSTGRES_POOL_SIZE: ${POSTGRES_POOL_SIZE}
#      HTTP_HEADER_LOG: ${HTTP_HEADER_LOG}
#      HTTP_BODY_LOG: ${HTTP_BODY_LOG}
#      HTTP_HOST: ${HTTP_HOST}
#      HTTP_PORT: ${HTTP_PORT}
#      REDIS_SERVER_URI: ${REDIS_SERVER_URI}
#      ACCESS_TOKEN_SECRET_KEY: ${ACCESS_TOKEN_SECRET_KEY}
#      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
#      JWT_TOKEN_EXPIRATION: ${JWT_TOKEN_EXPIRATION}
#      ADMIN_USER_TOKEN: ${ADMIN_USER_TOKEN}
#      PASSWORD_SALT: ${PASSWORD_SALT}
#      MESSAGE_BROKER_API: ${MESSAGE_BROKER_API}
#      MESSAGE_BROKER_USERNAME: ${MESSAGE_BROKER_USERNAME}
#      MESSAGE_BROKER_PASSWORD: ${MESSAGE_BROKER_PASSWORD}
#      MESSAGE_BROKER_ENABLED: ${MESSAGE_BROKER_ENABLED}
#      SCHEDULER_START_TIME: ${SCHEDULER_START_TIME}
#      SCHEDULER_PERIOD: ${SCHEDULER_PERIOD}
#      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
#      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
#      AWS_ENDPOINT: ${AWS_ENDPOINT}
#      AWS_SIGNING_REGION: ${AWS_SIGNING_REGION}
#      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
#      APP_ENV: ${APP_ENV}
#    volumes:
#      - "/srv/workout/logs:/srv/workout/logs"
  postgres:
    restart: always
    image: postgres:12
    command: -c max_connections=${POSTGRES_MAX_CONNECTION}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./tables.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    restart: always
    image: redis:6.2.6
    ports:
      - "6379:6379"
    environment:
      - DEBUG=false
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  localstack:
    container_name: "s3-for-workout"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=s3
      - DATA_DIR=/srv/workout/s3_storage/data
      - DEBUG=1
    volumes:
      - ./buckets:/docker-entrypoint-initaws.d
      - /srv/workout/s3_storage:/tmp/localstack
    restart: always

  frontend:
    image: workout-frontend:latest
    ports:
      - "3001:80"
    restart: always

  nginx-server:
    image: nginx
    network_mode: host
    volumes:
      - /srv/nginx_conf:/etc/nginx/conf.d
