version: "3.7"

services:
  localstack:
    container_name: "s3-container"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=s3
      - DATA_DIR=/srv/workout/s3_storage/data
      - DEBUG=1
    volumes:
      - ./buckets:/docker-entrypoint-initaws.d
      - /srv/workout/s3_storage:/tmp/localstack
    restart: always